@startuml

entity Game {
    Id : Guid
    --
    ' GameKeyCodePlaceholder
    --
    Name : string
    ' GamePropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
