# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Verify formatting
        run: dotnet format --verify-no-changes
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test Units
        run: dotnet test --no-build --verbosity normal BlazorCrudDotNet8.BusinessLogic.UnitTests
      - name: Test Server Components
        run: dotnet test --no-build --verbosity normal BlazorCrudDotNet8.Server.ComponentTests
      - name: Test Server Controllers
        run: dotnet test --no-build --verbosity normal BlazorCrudDotNet8.Server.ControllerTests
      - name: Test Client Components
        run: dotnet test --no-build --verbosity normal BlazorCrudDotNet8.Client.ComponentTests
      - name: Test Shared Components
        run: dotnet test --no-build --verbosity normal BlazorCrudDotNet8.Shared.ComponentTests
      - name: Run app in background
        run: dotnet run --project BlazorCrudDotNet8 &
      - name: Install powershell tools
        run: dotnet tool install --global PowerShell --version 7.4.4
      - name: Install playwright dependencies
        run: cd BlazorCrudDotNet8.AcceptanceTests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Test Acceptances
        run: dotnet test --no-build --verbosity normal BlazorCrudDotNet8.AcceptanceTests
name: .NET
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
